### ISSUE TITLE
[WPF] Method not found: SQLitePCL.raw.sqlite3_column_text

### ISSUE THREAD

**Issue by Keboo** [microsoft/appcenter-sdk-dotnet#1085]
### **Description**

I am not able to get the Analytics and Crashes to work on a WPF application.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a new WPF application. It can be found [here](https://github.com/Keboo/SimplyBudget/commit/1a452469b0d094980d6d6797a5123814ec68d9e5). 
2. Followed the directions listed on the [Getting Started with WPF/WinForms](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms)
3. Manually inserted an exception that occurs when you click Add then OK. I have done this both with and without a debugger attached and have re-launched the application several times to give it an opportunity to submit the logs. 

From the verbose output it appears there is an issue with SQLite.
I also live streamed my attempt at getting this working. You can find the recording [here](https://www.youtube.com/watch?v=77LdBdycH7E)

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)? WPF
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version r which PCL profile? .NET Framework 4.7.2
2. Which SDK version are you using? 2.2.1-preview
4. Which OS version did you experience the issue on? Windows 10 Pro 10.0.17763 Build 17763
5. What device version did you see this error on?  Were you using an emulator or a physical device? Physical device
6. What third party libraries are you using?  Packages.json
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CommonServiceLocator" version="2.0.4" targetFramework="net472" />
  <package id="MaterialDesignColors" version="1.2.0-ci1565" targetFramework="net472" />
  <package id="MaterialDesignThemes" version="2.6.0-ci1577" targetFramework="net472" />
  <package id="Microsoft.AppCenter" version="2.2.1-preview" targetFramework="net472" />
  <package id="Microsoft.AppCenter.Analytics" version="2.2.1-preview" targetFramework="net472" />
  <package id="Microsoft.AppCenter.Crashes" version="2.2.1-preview" targetFramework="net472" />
  <package id="MvvmLightLibs" version="5.4.1.1" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="12.0.2" targetFramework="net472" />
  <package id="sqlite-net-pcl" version="1.5.231" targetFramework="net472" />
  <package id="SQLitePCLRaw.bundle_green" version="2.0.0" targetFramework="net472" />
  <package id="SQLitePCLRaw.core" version="2.0.0" targetFramework="net472" />
  <package id="SQLitePCLRaw.lib.e_sqlite3" version="2.0.0" targetFramework="net472" />
  <package id="SQLitePCLRaw.provider.dynamic_cdecl" version="2.0.0" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net472" />
  <package id="System.Memory" version="4.5.3" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.6.0-preview5.19224.8" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.6.0-preview7.19362.9" targetFramework="net472" />
</packages>
```
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
```
'SimplyBudget.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\SimplyBudget.exe'. Symbols loaded.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\common7\ide\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'SimplyBudget.App..ctor'
Step into: Stepping over non-user code 'SimplyBudget.App.InitializeComponent'
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\MaterialDesignThemes.Wpf.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\MaterialDesignColors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\Microsoft.AppCenter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\Microsoft.AppCenter.Analytics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\Microsoft.AppCenter.Crashes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2019-08-14 08:52:56.297 [AppCenter] DEBUG: No named identifier found in appSecret; using as-is
2019-08-14 08:52:56.313 [AppCenter] DEBUG: Enabled TLS 1.2 explicitly as it was disabled.
2019-08-14 08:52:56.328 [AppCenter] DEBUG: AddChannel(core)
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\SQLite-net.dll'. Module was built without symbols.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Collections\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\SQLitePCLRaw.core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\SQLitePCLRaw.batteries_v2.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\SQLitePCLRaw.provider.dynamic_cdecl.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\SQLitePCLRaw.nativelibrary.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\System.Runtime.CompilerServices.Unsafe.dll'. Module was built without symbols.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Globalization\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Globalization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2019-08-14 08:52:56.578 [AppCenter] ERROR: An error occurred while initializing storage
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'System.String SQLitePCL.raw.sqlite3_column_text(SQLitePCL.sqlite3_stmt, Int32)'.
   at SQLite.SQLite3.ColumnString(sqlite3_stmt stmt, Int32 index)
   at SQLite.SQLiteCommand.ReadCol(sqlite3_stmt stmt, Int32 index, ColType type, Type clrType)
   at SQLite.SQLiteCommand.ExecuteScalar[T]()
   at SQLite.SQLiteConnection.ExecuteScalar[T](String query, Object[] args)
   at SQLite.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks, Object key)
   at SQLite.SQLiteConnectionWithLock..ctor(SQLiteConnectionString connectionString, SQLiteOpenFlags openFlags)
   at SQLite.SQLiteAsyncConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks, Object key)
   at SQLite.SQLiteAsyncConnection..ctor(String databasePath, Boolean storeDateTimeAsTicks, Object key)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AppCenter.Storage.StorageAdapter.<InitializeStorageAsync>b__9_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AppCenter.Storage.Storage.<InitializeDatabaseAsync>d__19.MoveNext()
2019-08-14 08:52:56.599 [AppCenter] INFO: App Center SDK configured successfully.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Linq.Expressions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Linq.Expressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Threading.Tasks\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.Tasks.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2019-08-14 08:52:56.606 [AppCenter] DEBUG: AddChannel(analytics)
2019-08-14 08:52:56.615 [AppCenterAnalytics] DEBUG: SessionTracker.Resume
2019-08-14 08:52:56.628 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x23c8 has exited with code 0 (0x0).
The thread 0x5b94 has exited with code 0 (0x0).
The thread 0x462c has exited with code 0 (0x0).
2019-08-14 08:52:57.072 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2019-08-14 08:52:57.083 [AppCenter] INFO: 'Analytics' service started.
2019-08-14 08:52:57.088 [AppCenter] DEBUG: AddChannel(crashes)
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2019-08-14 08:52:57.605 [AppCenter] INFO: 'Crashes' service started.
2019-08-14 08:52:57.607 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'core'
The thread 0x5304 has exited with code 0 (0x0).
The thread 0x59a8 has exited with code 0 (0x0).
The thread 0x365c has exited with code 0 (0x0).
2019-08-14 08:52:57.816 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'core'
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\GalaSoft.MvvmLight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ObjectModel\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Dev\SimplyBudget\SimplyBudget\bin\Debug\GalaSoft.MvvmLight.Platform.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Threading\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\Users\kitok\AppData\Local\Temp\VisualStudio.XamlDiagnostics.6276\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll'. 
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\system32\WinMetadata\Windows.UI.winmd'. Module was built without symbols.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd'. Module was built without symbols.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimplyBudget.exe' (CLR v4.0.30319: SimplyBudget.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x53b8 has exited with code 0 (0x0).
The thread 0x49d4 has exited with code 0 (0x0).
The thread 0x804 has exited with code 0 (0x0).
The thread 0x908 has exited with code 0 (0x0).
The thread 0x3c98 has exited with code 0 (0x0).
2019-08-14 08:53:50.545 [AppCenterAnalytics] DEBUG: SessionTracker.Pause
The program '[6276] SimplyBudget.exe: Program Trace' has exited with code 0 (0x0).
The program '[6276] SimplyBudget.exe' has exited with code -1073740771 (0xc000041d).

```

**Comment by annakocheshkova** [comment]
Hi @Keboo, this is a version conflict. In SQLitePCL.raw > 2.0.0 there were [breaking changes](https://github.com/ericsink/SQLitePCL.raw/blob/master/v2.md#source-level-breaking-changes) introduced. Please downgrade the package in your project.

**Comment by Keboo** [comment]
@annakocheshkova thank you for the reply. After playing around with it, it appears my problems came from the NuGet package manager Dependency behavior. Setting it to either Lowest or Highest results in version conflict issues (similar to the one linked above). 
My packages.config now looks like this and it appears to be working:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CommonServiceLocator" version="2.0.4" targetFramework="net472" />
  <package id="MaterialDesignColors" version="1.2.0-ci1565" targetFramework="net472" />
  <package id="MaterialDesignThemes" version="2.6.0-ci1577" targetFramework="net472" />
  <package id="Microsoft.AppCenter" version="2.2.1-preview" targetFramework="net472" />
  <package id="Microsoft.AppCenter.Analytics" version="2.2.1-preview" targetFramework="net472" />
  <package id="Microsoft.AppCenter.Crashes" version="2.2.1-preview" targetFramework="net472" />
  <package id="Microsoft.NETCore.Platforms" version="1.0.1" targetFramework="net472" />
  <package id="Microsoft.Win32.Primitives" version="4.0.1" targetFramework="net472" />
  <package id="MvvmLightLibs" version="5.4.1.1" targetFramework="net472" />
  <package id="NETStandard.Library" version="1.6.0" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="12.0.2" targetFramework="net472" />
  <package id="sqlite-net-pcl" version="1.3.1" targetFramework="net472" />
  <package id="SQLitePCLRaw.bundle_green" version="1.1.14" targetFramework="net472" />
  <package id="SQLitePCLRaw.core" version="1.1.14" targetFramework="net472" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.linux" version="1.1.14" targetFramework="net472" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.osx" version="1.1.14" targetFramework="net472" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.v110_xp" version="1.1.14" targetFramework="net472" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.net45" version="1.1.14" targetFramework="net472" />
  <package id="System.AppContext" version="4.1.0" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net472" />
  <package id="System.Collections" version="4.0.11" targetFramework="net472" />
  <package id="System.Collections.Concurrent" version="4.0.12" targetFramework="net472" />
  <package id="System.Console" version="4.0.0" targetFramework="net472" />
  <package id="System.Diagnostics.Debug" version="4.0.11" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.0.0" targetFramework="net472" />
  <package id="System.Diagnostics.Tools" version="4.0.1" targetFramework="net472" />
  <package id="System.Diagnostics.Tracing" version="4.1.0" targetFramework="net472" />
  <package id="System.Globalization" version="4.0.11" targetFramework="net472" />
  <package id="System.Globalization.Calendars" version="4.0.1" targetFramework="net472" />
  <package id="System.IO" version="4.1.0" targetFramework="net472" />
  <package id="System.IO.Compression" version="4.1.0" targetFramework="net472" />
  <package id="System.IO.Compression.ZipFile" version="4.0.1" targetFramework="net472" />
  <package id="System.IO.FileSystem" version="4.0.1" targetFramework="net472" />
  <package id="System.IO.FileSystem.Primitives" version="4.0.1" targetFramework="net472" />
  <package id="System.Linq" version="4.1.0" targetFramework="net472" />
  <package id="System.Linq.Expressions" version="4.1.0" targetFramework="net472" />
  <package id="System.Memory" version="4.5.3" targetFramework="net472" />
  <package id="System.Net.Http" version="4.1.0" targetFramework="net472" />
  <package id="System.Net.Primitives" version="4.0.11" targetFramework="net472" />
  <package id="System.Net.Sockets" version="4.1.0" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.6.0-preview5.19224.8" targetFramework="net472" />
  <package id="System.ObjectModel" version="4.0.12" targetFramework="net472" />
  <package id="System.Reflection" version="4.1.0" targetFramework="net472" />
  <package id="System.Reflection.Extensions" version="4.0.1" targetFramework="net472" />
  <package id="System.Reflection.Primitives" version="4.0.1" targetFramework="net472" />
  <package id="System.Resources.ResourceManager" version="4.0.1" targetFramework="net472" />
  <package id="System.Runtime" version="4.1.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.6.0-preview7.19362.9" targetFramework="net472" />
  <package id="System.Runtime.Extensions" version="4.1.0" targetFramework="net472" />
  <package id="System.Runtime.Handles" version="4.0.1" targetFramework="net472" />
  <package id="System.Runtime.InteropServices" version="4.1.0" targetFramework="net472" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.0.0" targetFramework="net472" />
  <package id="System.Runtime.Numerics" version="4.0.1" targetFramework="net472" />
  <package id="System.Security.Cryptography.Algorithms" version="4.2.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.Encoding" version="4.0.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.Primitives" version="4.0.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.1.0" targetFramework="net472" />
  <package id="System.Text.Encoding" version="4.0.11" targetFramework="net472" />
  <package id="System.Text.Encoding.Extensions" version="4.0.11" targetFramework="net472" />
  <package id="System.Text.RegularExpressions" version="4.1.0" targetFramework="net472" />
  <package id="System.Threading" version="4.0.11" targetFramework="net472" />
  <package id="System.Threading.Tasks" version="4.0.11" targetFramework="net472" />
  <package id="System.Threading.Timer" version="4.0.1" targetFramework="net472" />
  <package id="System.Xml.ReaderWriter" version="4.0.11" targetFramework="net472" />
  <package id="System.Xml.XDocument" version="4.0.11" targetFramework="net472" />
</packages>
```
