### ISSUE TITLE
When I invoke start method, I got StackOverflowException

### ISSUE THREAD

**Issue by poumason** [microsoft/appcenter-sdk-dotnet#1117]
### **Description**

I want to integrated App Center SDK preview on WPF project.
When the code invoke Start method, the vs got the StackOverflowException.
I can't got any information in output console.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. install  2.3.0-preview nuget 
2. invoke  AppCenter.Start()

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WPF
2. Which SDK version are you using?
    - 2.3.0-preview
4. Which OS version did you experience the issue on?
    - Windows 10
6. What third party libraries are you using? 
    - SQLite-net, Version=1.5.231.0
    - SQLitePCLRaw.core, Version=1.1.12.351
    - SQLitePCLRaw.provider.sqlite3, Version=1.1.12.351

**Comment by poumason** [comment]
I fund the *.csproj have the same library reference, they just use the difference version:

```
<Reference Include="SQLite-net, Version=1.1.0.0, Culture=neutral, processorArchitecture=MSIL">
  <HintPath>..\..\packages\sqlite-net-pcl.1.3.1\lib\netstandard1.1\SQLite-net.dll</HintPath>
</Reference>
<Reference Include="SQLitePCLRaw.batteries_green, Version=1.0.0.0, Culture=neutral, PublicKeyToken=a84b7dcfb1391f7f, processorArchitecture=MSIL">
  <HintPath>..\..\packages\SQLitePCLRaw.bundle_green.1.1.2\lib\net45\SQLitePCLRaw.batteries_green.dll</HintPath>
</Reference>
<Reference Include="SQLitePCLRaw.batteries_v2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8226ea5df37bcae9, processorArchitecture=MSIL">
  <HintPath>..\..\packages\SQLitePCLRaw.bundle_green.1.1.2\lib\net45\SQLitePCLRaw.batteries_v2.dll</HintPath>
</Reference>
<Reference Include="SQLitePCLRaw.core, Version=1.1.12.351, Culture=neutral, PublicKeyToken=1488e028ca7ab535, processorArchitecture=MSIL">
  <HintPath>..\..\packages\SQLitePCLRaw.core.1.1.12\lib\net45\SQLitePCLRaw.core.dll</HintPath>
</Reference>
<Reference Include="SQLitePCLRaw.provider.e_sqlite3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9c301db686d0bd12, processorArchitecture=MSIL">
  <HintPath>..\..\packages\SQLitePCLRaw.provider.e_sqlite3.net45.1.1.2\lib\net45\SQLitePCLRaw.provider.e_sqlite3.dll</HintPath>
</Reference>
<Reference Include="SQLitePCLRaw.provider.sqlite3, Version=1.1.12.351, Culture=neutral, PublicKeyToken=62684c7b4f184e3f, processorArchitecture=MSIL">
  <HintPath>..\..\packages\SQLitePCLRaw.provider.sqlite3.net40.1.1.12\lib\net40\SQLitePCLRaw.provider.sqlite3.dll</HintPath>
</Reference>
```

I try remove the same library, the issue be solved. 
But I get other exception:
```
2019-09-12 12:43:33.035 [AppCenter] ERROR: An error occurred while initializing storage
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
   at SQLitePCL.SQLite3Provider_bait.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.sqlite3_libversion_number()
   at SQLite.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks, Object key)
   at SQLite.SQLiteConnectionWithLock..ctor(SQLiteConnectionString connectionString, SQLiteOpenFlags openFlags)
   at SQLite.SQLiteAsyncConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks, Object key)
   at SQLite.SQLiteAsyncConnection..ctor(String databasePath, Boolean storeDateTimeAsTicks, Object key)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AppCenter.Storage.StorageAdapter.<InitializeStorageAsync>b__9_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AppCenter.Storage.Storage.<InitializeDatabaseAsync>d__19.MoveNext()
```

**Comment by MatkovIvan** [comment]
Hi @poumason 

I guess the problem here is two conflicting SQLite providers (`SQLitePCLRaw.provider.*`).
Based on [the doc](https://github.com/ericsink/SQLitePCL.raw#included-providers):
> "sqlite3" -- This matches the name of the system-provided SQLite on iOS (which is fine), and Android (which is not allowed). And it matches the official name of builds provided at sqlite.org.

So I suggest you remove that extra provider and use the same one that used by App Center SDK.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if it's still the case for you or you have more questions.
