### ISSUE TITLE
AppCenter throws an SQLiteException at startup

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/appcenter-sdk-dotnet#1313]
### **Description**

I'm using the `AppCenter.Analytics` and `AppCenter.Crashes` packages in a UWP application. As soon as I start up the app and use any of the `AppCenter` APIs, I get a bunch of `SQLiteException`s saying:

> Could not open database file: Microsoft.AppCenter.Storage (CannotOpen)

[Here's a screen with the exception](https://user-images.githubusercontent.com/10199417/73582397-4829d500-448d-11ea-87be-be1ab5cb27e8.png).

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a blank UWP app
2. Install these packages:

- `AppCenter.Analytics 2.6.4`
- `AppCenter.Crashes 2.6.4`
- `sqlite-net-pcl 1.7.302-beta`

3. Add the following line:

```csharp
AppCenter.Start("<CLIENT_ID>", typeof(Crashes), typeof(Analytics));
```

4. Start the app

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - UWP
2. Which SDK version are you using?
    - 2.6.4
3. Which OS version did you experience the issue on?
    - Any W10 build >= 17763 (that's my min SDK)
4. What third party libraries are you using? 
    - `sqlite-net-pcl 1.7.302-beta`
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

> [AppCenter] DEBUG: No named identifier found in appSecret; using as-is
[AppCenter] DEBUG: AddChannel(core)
Exception thrown: 'SQLite.SQLiteException' in SQLite-net.dll
Exception thrown: 'SQLite.SQLiteException' in System.Private.CoreLib.dll
Exception thrown: 'SQLite.SQLiteException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in Microsoft.AppCenter.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
'LoadedGlitchRepro.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.27909.0_x64__8wekyb3d8bbwe\System.Diagnostics.StackTrace.dll'. 
[AppCenter] ERROR: An error occurred while initializing storage
Microsoft.AppCenter.Storage.StorageException: SQLite errorCode=CannotOpen ---> SQLite.SQLiteException: Could not open database file: Microsoft.AppCenter.Storage (CannotOpen)
   at SQLite.SQLiteConnection..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnectionPool.Entry.Connect()
   at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString connectionString)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass32_0`1.<WriteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AppCenter.Storage.StorageAdapter.CreateTableAsync[T]()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Storage.StorageAdapter.CreateTableAsync[T]()
   at Microsoft.AppCenter.Storage.Storage.InitializeDatabaseAsync()
Exception thrown: 'SQLite.SQLiteException' in SQLite-net.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in Microsoft.AppCenter.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
[AppCenter] INFO: App Center SDK configured successfully.
[AppCenter] DEBUG: AddChannel(crashes)
Exception thrown: 'SQLite.SQLiteException' in SQLite-net.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in Microsoft.AppCenter.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
[AppCenter] INFO: 'Crashes' service started.
[AppCenter] DEBUG: AddChannel(analytics)
Exception thrown: 'SQLite.SQLiteException' in SQLite-net.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in Microsoft.AppCenter.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
[AppCenter] INFO: 'Analytics' service started.
[AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'core'
[AppCenterAnalytics] DEBUG: SessionTracker.Resume
[AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
[AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
[AppCenter] DEBUG: Invoke FilteringLog event for channel 'core'
[AppCenter] ERROR: Error persisting log
Microsoft.AppCenter.Storage.StorageException: The storage operation failed ---> SQLite.SQLiteException: Could not open database file: Microsoft.AppCenter.Storage (CannotOpen)
   at SQLite.SQLiteConnection..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnectionPool.Entry.Connect()
   at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString connectionString)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass32_0`1.<WriteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass11_0.<PutLog>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass24_0.<AddTaskToQueue>b__0()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass24_0.<AddTaskToQueue>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AppCenter.Channel.Channel.PersistLogAsync(Log log, State state)
[AppCenter] ERROR: Error persisting log
Microsoft.AppCenter.Storage.StorageException: The storage operation failed ---> SQLite.SQLiteException: Could not open database file: Microsoft.AppCenter.Storage (CannotOpen)
   at SQLite.SQLiteConnection..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnectionPool.Entry.Connect()
   at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString connectionString)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass32_0`1.<WriteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass11_0.<PutLog>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass24_0.<AddTaskToQueue>b__0()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass24_0.<AddTaskToQueue>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AppCenter.Channel.Channel.PersistLogAsync(Log log, State state)
Exception thrown: 'SQLite.SQLiteException' in SQLite-net.dll
Exception thrown: 'SQLite.SQLiteException' in System.Private.CoreLib.dll
Exception thrown: 'SQLite.SQLiteException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in Microsoft.AppCenter.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
Exception thrown: 'SQLite.SQLiteException' in SQLite-net.dll
Exception thrown: 'SQLite.SQLiteException' in System.Private.CoreLib.dll
Exception thrown: 'SQLite.SQLiteException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in Microsoft.AppCenter.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Storage.StorageException' in System.Private.CoreLib.dll

**Comment by guperrot** [comment]
Hi, this is most likely because that version of sqlite-net-pcl is using SQLitePCLRaw.bundle_green 2.0 while AppCenter is using an old version and thus causing a conflict.

We however are going to release in February a version that uses SQLitePCLRaw.bundle_green 2.0 which would be the same dependency as sqlite-net-pcl 1.7 beta.

**Comment by Sergio0694** [comment]
@guperrot **YES!** 🚀
Thank you for the quick reply, and I'm **so** glad to hear a fix for this is coming with such a short ETA!
Looking forward to the new update then, thank you for your help!

**Comment by guperrot** [comment]
To be fair, the feature was actually requested a long time ago by other users and it took a long time to do. You can see https://github.com/microsoft/appcenter-sdk-dotnet/issues/1264 and other related issues.

**Comment by Sergio0694** [comment]
@guperrot Ah, I see 👍
I wonder if `AppCenter` upgrading to the new `SQLite` lib will also make it compatible with ARM64 too? I know that's been a much requested feature for quite a while but I still don't know the official ETA on that.

**Comment by guperrot** [comment]
Yes the only reason we are currently incompatible with arm64 is because of the outdated dependency on sqlite. Updating to v2 solves the arm64 architecture support.
