### ISSUE TITLE
FileNotFoundException and DllNotFoundException in AppCenter code with self-contained WPF app

### ISSUE THREAD

**Issue by jnm2** [microsoft/appcenter-sdk-dotnet#1390]
I'm not sure how I would begin to repro this. FileNotFoundException and DllNotFoundException showed up with no exception message and only Microsoft code on the call stack:

```
System.DllNotFoundException: Dll was not found.
  at __std_type_info_destroy_list(__type_info_node* )
  at __scrt_uninitialize_type_info()
  at _app_exit_callback()
  at <CrtImplementationDetails>.LanguageSupport.DomainUnload(Object A_0, EventArgs A_1)
  at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
  at System.AppContext.OnProcessExit()
```

```
System.IO.FileNotFoundException: 
  at System.Windows.Forms.Screen.get_AllScreens()
  at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.WindowIntersectsWithAnyScreen(Object window)
  at CallSite.Target(Closure , CallSite , Type , Object )
  at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
  at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.IsAnyWindowNotMinimized()
  at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.WinEventHook(IntPtr winEventHookHandle, UInt32 eventType, IntPtr windowHandle, Int32 objectId, Int32 childId, UInt32 eventThreadId, UInt32 eventTimeInMilliseconds)
```

### **Details**

.NET Core 3.1 WPF with PublishSingleFile and PublishTrimmed. Csproj contents:

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationManifest>App.manifest</ApplicationManifest>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AmbientTasks" Version="1.0.0" />
    <PackageReference Include="Humanizer.Core" Version="2.7.9" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="3.0.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="3.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.8" PrivateAssets="all" />
    <PackageReference Include="PropertyChangedAnalyzers" Version="3.2.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Settings.settings" Generator="SettingsSingleFileGenerator" LastGenOutput="Settings.Designer.cs" />
    <Compile Update="Settings.Designer.cs" DesignTimeSharedInput="True" AutoGen="True" DependentUpon="Settings.settings" />
  </ItemGroup>

</Project>
```

**Comment by vvechkanov** [comment]
Hey, @jnm2, thanks for getting in touch. I am trying to reproduce this issue. Could you please share when this Exception appears. I mean how do you use SDK in the moment crash appears. 
For now, I tried to create a simple WPF application with the same dependencies and settings and it launches correctly.

Also, could you please [enable verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/uwp#adjust-the-log-level), to get more details of the exception reason. For that please add line `AppCenter.LogLevel = LogLevel.Verbose` before `AppCenter.Start`.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.

**Comment by jnm2** [comment]
Sorry about that. I haven't been able to reproduce the crash.

**Comment by aesim-tech** [comment]
Hi, 
Not sure if it helps but I just experienced the same crash with my program. I am using Dotnet 5.0 WPF with PublishSingleFile and PublishTrimmed.

Crash log: 

```
Package: UPSIM.UI.WPF
Version: 2020.12.8.0
OS: WINDOWS
Windows: 10.0.19042
Date: 2020-12-15T18:42:33.0872867Z

Exception Stack:
System.DllNotFoundException: Dll was not found.
  at __std_type_info_destroy_list(__type_info_node* )
  at __scrt_uninitialize_type_info()
  at _app_exit_callback()
  at <CrtImplementationDetails>.LanguageSupport.DomainUnload(Object A_0, EventArgs A_1)
  at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
  at System.AppContext.OnProcessExit() 
```

I am not able to reproduce this issue either.

**Comment by AnastasiaKubova** [comment]
Hi! Could you please share additional information about this issue? Could you please [enable verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/uwp#adjust-the-log-level) and share reproducing steps? Unfortunately, we can't reproduce this issue on our side and any other additional information will be helpful to investigate this.

**Comment by aesim-tech** [comment]
Hi Anastasia,
Sorry but this issue happened on a client computer and I am not able to reproduce it locally. I just copied the crash log in case it would help. It is not critical at all. 

What is weird is the crash happened 25 hours after the user closed the program...   🤨
![image](https://user-images.githubusercontent.com/62940363/102497962-581bba80-4047-11eb-8503-b0fc920f0bfd.png)

**Comment by TomLeroc** [comment]
I too have encountered this issue with a self contained .net core app with WPF elements.
This exception is occurring on the FinalizerThread in response to the application being closed.

```
> pe -lines
Exception object: 0000027a5dcc8490
Exception type:   System.DllNotFoundException
Message:          Dll was not found.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    000000F473E7F3C0 0000000000000000 DirectWriteForwarder.dll!<Module>.__std_type_info_destroy_list(__type_info_node*)+0x1
    000000F473E7F470 0000027A0341F8AA DirectWriteForwarder.dll!<Module>.__scrt_uninitialize_type_info()+0x3a
    000000F473E7F4B0 0000027A0341DD06 DirectWriteForwarder.dll!<Module>._app_exit_callback()+0x116
    000000F473E7F590 0000027A0341F320 DirectWriteForwarder.dll!<Module>.<CrtImplementationDetails>.LanguageSupport.DomainUnload(System.Object, System.EventArgs)+0x30
    000000F473E7F5C0 0000027A0342BF5B DirectWriteForwarder.dll!<CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(System.Object, System.EventArgs)+0x9b
    000000F473E7F680 00000001801EB4CE System.Private.CoreLib.dll!System.AppContext.OnProcessExit()+0x5e [/_/src/libraries/System.Private.CoreLib/src/System/AppContext.cs @ 81]

StackTraceString: <none>
HResult: 80131524
```

I'm intrigued by a comment in 
https://github.com/dotnet/wpf/blame/main/src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/main.cpp
```    
    // Previously we had this as a class dtor but we found out that
    // we can't use a destructor due to an issue with how it's registered to be called on exit:
    // A compiler-generated function calls _atexit_m_appdomain(). But that generated function is transparenct,
    // which causes a violation because _atexit_m_appdomain() is Critical.
    __declspec(noinline) void UnInitialize()
    {
        MS::Internal::NativeWPFDLLLoader::UnloadDWrite();

        MS::Internal::NativeWPFDLLLoader::ClearDWriteCreateFactoryFunctionPointer();
        //
        // Finalizers run after this dtor so if we unload dwrite now
        // we may end up making calls into unloaded code. Yes, this 
        // is a "leak" but it's only really a leak if no more WPF 
        // AppDomains are present and it's a single leak since only
        // one instance of a version of a CLR may be in proc at 
        // once.
        //
        // We could also use a critical finalizer for the handle
        // but that requires changing this code quite a bit plus
        // if other critical finalizers ever call dwrite code
        // we have the same problem again.
        //
        // MS::Internal::NativeWPFDLLLoader::UnloadDWrite();
    }
```
I have a mini dump, but I don't know whether it is repeatable.
