### ISSUE TITLE
System.Environment.FailFast results in no exception logged in App Center

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter-sdk-dotnet#1511]
I have the following call stack that is not being picked up by App Center so we have no knowledge of these types of issues occurring at client sites. Apart from users reporting them.

This has been extracted from EventViewer:

Application: Compucare.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Unrecoverable system error.
Stack:
  at System.Environment.FailFast(System.String)
  at System.Windows.Documents.Speller.ScanRange(System.Windows.Documents.ITextPointer, System.Windows.Documents.ITextPointer, Int64)
  at System.Windows.Documents.Speller.OnIdle(System.Object)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
  at System.Windows.Threading.DispatcherOperation.InvokeImpl()
  at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
  at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
  at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
  at System.Windows.Threading.DispatcherOperation.Invoke()
  at System.Windows.Threading.Dispatcher.ProcessQueue()
  at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
  at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
  at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
  at System.Windows.Application.RunDispatcher(System.Object)
  at System.Windows.Application.RunInternal(System.Windows.Window)
  at StreetsHeaver.Columbus.Shell.App.Main()

**Comment by AnastasiaKubova** [comment]
Hi, @james1301 ! 
Thanks for getting in touch with us!
Based on docs about [FastFail](https://docs.microsoft.com/en-us/dotnet/api/system.environment.failfast?view=net-5.0) there are no ways to catch this exception.

> This method terminates a process without running any active try/finally blocks or finalizers.

> The Environment.FailFast method writes the message string to the Windows Application event log, creates a dump of your application, and then terminates the current process. The message string is also included in error reporting to Microsoft.

This method calls hard termination of the process and it wouldn't call any events for handling exceptions.

**Comment by james1301** [comment]
Yes that was my general take on it. Just leaves a little hole in knowing about these errors. I was hoping there would be some way of getting some accessibility to these types of errors. Like reaching into event log to try to pick any of these up etc, or picking up that the dump has been made to send some acknowledgement about it? Or hooking into the error reporting to Microsoft?

Just concerned of how many and how long these problems have been occurring as I have no idea as we have 100's of clients.

**Comment by AnastasiaKubova** [comment]
Because the App Center SDK is an in-process crash reporter there are no ways to catch these crashes. We used a watson for catching crashes in UWP but it was dropped in the [2.2.1-preview](https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/CHANGELOG.md#uwp-5) version of App Center SDK due to restrictions and we have no plans to use it again.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
