### ISSUE TITLE
Distribute crash when targetSDK is set to android 14

### ISSUE THREAD

**Issue by SarthakB26** [microsoft/appcenter-sdk-dotnet#1774]
### **Description**
Distribute crashes when trying to get a version update when application targeting android 14.
Set your target SDK to 34 (Android 14)

One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when registering the receiver

Version : 5.0.3

```
Fatal Exception: java.lang.SecurityException: xxxxxxxxxxxxxx: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
       at android.os.Parcel.createException(Parcel.java:3041)
       at android.os.Parcel.readException(Parcel.java:3024)
       at android.os.Parcel.readException(Parcel.java:2966)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
       at com.microsoft.appcenter.distribute.install.session.SessionReleaseInstaller.registerListeners(SessionReleaseInstaller.java:236)
       at com.microsoft.appcenter.distribute.install.session.SessionReleaseInstaller.install(SessionReleaseInstaller.java)
       at com.microsoft.appcenter.distribute.UpdateInstaller.install(UpdateInstaller.java:93)
       at com.microsoft.appcenter.distribute.Distribute.setInstalling(Distribute.java:1931)
       at com.microsoft.appcenter.distribute.ReleaseDownloadListener$3.run(ReleaseDownloadListener.java:97)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by SarthakB26** [comment]
Note : App crashed on Android 14 device even if we are targeting android api 33 not 34.

**Comment by MikhailSuendukov** [comment]
Hello, the [AppCenter .NET SDK v5.0.4](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/5.0.4) has been released, including a fix for this issue. Therefore, I am closing this issue.
