### ISSUE TITLE
Analytics.TrackEvent is broken after handling UnhandledException event in UWP App

### ISSUE THREAD

**Issue by jsiemens** [Microsoft/AppCenter-SDK-DotNet#613]
After handling an otherwise unhandled exception, Analytics.TrackEvent becomes broken.

I handle an unhandled exception as so in App.xaml.cs:

        public App()
        {
            this.UnhandledException += App_UnhandledException;
        }

        private void App_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            e.Handled = true;
        }

Henceforth, all calls to Analytics.TrackEvent generate the following message in the debug output:

[AppCenter] ERROR: Error persisting log
Microsoft.AppCenter.Storage.StorageException: The operation has been cancelled
   at Microsoft.AppCenter.Storage.Storage.PutLog(String channelName, Log log)
   at Microsoft.AppCenter.Channel.Channel.<PersistLogAsync>d__39.MoveNext()
[AppCenter] ERROR: Error persisting log

The events are indeed not persisted.

**Comment by guperrot** [comment]
Hi, is the rest of the app working after doing that?

**Comment by guperrot** [comment]
I can confirm the bug, we are shutting down channel and making sure logs are persisted before application exits in error. Except we can't know if exception is handled. We will discuss what we can do to support this scenario.
