### ISSUE TITLE
Android: Java.Lang.LinkageError on TrackError()

### ISSUE THREAD

**Issue by kkarasevich** [Microsoft/AppCenter-SDK-DotNet#684]
### **Description**

Calling Crashes.TrackError() throws the following exception

Java.Lang.LinkageError: no static method "Lcom/microsoft/appcenter/crashes/WrapperSdkExceptionManager;.trackException(Lcom/microsoft/appcenter/crashes/ingestion/models/Exception;Ljava/util/Map;)V"

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <c7ddbfae5e2d447995a8f217776227bb>:0 
  at Java.Interop.JniEnvironment+StaticMethods.GetStaticMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <a4db6126c52046eaa6c33ab43f6b26ea>:0 
  at Android.Runtime.JNIEnv.GetStaticMethodID (System.IntPtr jclass, System.String name, System.String sig) [0x00007] in <0aa9291b011d4230a105e5d7c72b0c22>:0 
  at Com.Microsoft.Appcenter.Crashes.WrapperSdkExceptionManager.TrackException (Com.Microsoft.Appcenter.Crashes.Ingestion.Models.Exception p0, System.Collections.Generic.IDictionary`2[TKey,TValue] p1) [0x00016] in <54a5cb55a21a4f20a837868a50e801af>:0 
  at Microsoft.AppCenter.Crashes.Crashes.PlatformTrackError (System.Exception exception, System.Collections.Generic.IDictionary`2[TKey,TValue] properties) [0x00007] in <8050a26b8c294e6dbb3d3fc36802ba10>:0 
  at Microsoft.AppCenter.Crashes.Crashes.TrackError (System.Exception exception, System.Collections.Generic.IDictionary`2[TKey,TValue] properties) [0x00013] in <8050a26b8c294e6dbb3d3fc36802ba10>:0 
  at DT.Takson.Android.AppCenterService.TrackError (System.Exception ex, System.Collections.Generic.Dictionary`2[TKey,TValue] properties) [0x00001] in /Users/konstantin/gitProjects/taxigorod/DT.Takson.Android/Services/AppCenterService.cs:17 
  at DT.Takson.Core.ErrorHandler.Handle (System.Exception ex, System.Boolean isSilent, System.Boolean isCritical, System.String action) [0x00072] in /Users/konstantin/gitProjects/taxigorod/DT.Takson.Core/Services/ErrorHandler.cs:53 
  at DT.Takson.Core.ViewModels.AccountViewModel+<ReloadUserInfo>d__86.MoveNext () [0x002a6] in /Users/konstantin/gitProjects/taxigorod/DT.Takson.Core/ViewModels/AccountViewModel.cs:250 
  --- End of managed Java.Lang.LinkageError stack trace ---
java.lang.NoSuchMethodError: no static method "Lcom/microsoft/appcenter/crashes/WrapperSdkExceptionManager;.trackException(Lcom/microsoft/appcenter/crashes/ingestion/models/Exception;Ljava/util/Map;)V"
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

### **Details**

Platform: Xamarin.Android
Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/konstantin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Nuget package varsion: 1.6.1

**Comment by guperrot** [comment]
Hi, it looks like a common problem when updating package with a stale build cache.
Please close Visual Studio, clean all obj and bin folders (some files can persist even after a solution clean within VS) and try building again.
If you have a packages directory at root and using packages.config file, please also delete that folder and restore nuget packages before trying again.

**Comment by kkarasevich** [comment]
That works! Thank you

**Comment by guperrot** [comment]
You are welcome.
