### ISSUE TITLE
Automatically crashes after a few seconds when 'Crashes' is enabled, deserializeLog not found

### ISSUE THREAD

**Issue by gunvld** [Microsoft/AppCenter-SDK-DotNet#696]
### **Description**

I started using App Center a few weeks ago, it registered all crashes and errors. However , the App Center SDK itself is now crashing my application when I enable Crashes. Analytics and Push works fine. This happened 1 day after I updated my phone (Galaxy S7 Edge) to Android 8, however this is also happening on an Xperia Z1, Android 4.4.2. 

Now I can't track crashes or the app crashes on me. It is giving a Java.Lang.NoSuchMethodError: No interface method deserializeLog error (see logs below). I tried debugging it , but it crashes(in no particular location in the code) a few seconds after AppCenter.Start. Is deserializeLog a method that only exists between Android 5 and 7?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. AppCenter.Start with Analytics, Crashes and Push turned on, in App.xaml.cs, first thing.
2. Wait a few seconds while the app center is starting
3. Crash

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms, happens on Android
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.0.
2. Which SDK version are you using?
    - Happens on 1.6 and 1.7
4. Which OS version did you experience the issue on?
    - Android 4.4.2, Android 8.0
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Galaxy S7 Edge physical device, Xperia Z1 physical device
6. What third party libraries are you using? 
	Rg.Plugins.Popup                    {1.1.4.145-pre}                          Poopy1                                                                                                                                                 
	Newtonsoft.Json                     {11.0.2}                                 Poopy1                                                                                                                                                 
	Xam.Plugins.Settings                {3.1.1}                                  Poopy1                                                                                                                                                 
	Xam.Plugin.DeviceInfo               {4.0.0.13}                               Poopy1                                                                                                                                                 
	TK.CustomMap                        {2.0.1}                                  Poopy1                                                                                                                                                 
	Com.Airbnb.Xamarin.Forms.Lottie     {2.5.4}                                  Poopy1                                                                                                                                                 
	Xamarin.FFImageLoading.Forms        {2.3.6}                                  Poopy1                                                                                                                                                 
	Plugin.Permissions                  {2.2.1}                                  Poopy1                                                                                                                                                 
	Microsoft.AppCenter.Analytics       {1.7.0}                                  Poopy1                                                                                                                                                 
	Xamarin.FFImageLoading.Transform... {2.3.6}                                  Poopy1                                                                                                                                                 
	Toasts.Forms.Plugin                 {3.3.2}                                  Poopy1                                                                                                                                                 
	Xam.Plugin.Geolocator               {4.2.0}                                  Poopy1                                                                                                                                                 
	Xamarin.Forms.Maps                  {2.5.0.280555}                           Poopy1                                                                                                                                                 
	PropertyChanged.Fody                {2.4.0}                                  Poopy1                                                                                                                                                 
	FreshEssentials                     {2.1.3}                                  Poopy1                                                                                                                                                 
	JWT                                 {4.0.0}                                  Poopy1                                                                                                                                                 
	Xamarin.FFImageLoading.Svg.Forms    {2.3.6}                                  Poopy1                                                                                                                                                 
	System.IdentityModel.Tokens.Jwt     {5.2.2}                                  Poopy1                                                                                                                                                 
	MonkeyCache                         {0.1.0.10-beta}                          Poopy1                                                                                                                                                 
	Xam.Plugin.Media                    {3.1.3}                                  Poopy1                                                                                                                                                 
	Microsoft.AppCenter.Push            {1.7.0}                                  Poopy1                                                                                                                                                 
	NETStandard.Library                 {2.0.1}                                  Poopy1                                                                                                                                                 
	Microsoft.AppCenter.Crashes         {1.7.0}                                  Poopy1                                                                                                                                                 
	Fody                                {3.0.1}                                  Poopy1                                                                                                                                                 
	Refit                               {4.3.0}                                  Poopy1                                                                                                                                                 
	Xamarin.Forms                       {3.0.0.446417}                           Poopy1                                                                                                                                                 
	MonkeyCache.SQLite                  {0.1.0.10-beta}                          Poopy1                                                                                                                                                 
	Xam.Plugins.Forms.ImageCircle       {2.0.2}                                  Poopy1                                                                                                                                                 
	Microsoft.AppCenter                 {1.7.0}                                  Poopy1  
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
The log(removed redundant info) same error every time:
`07-03 14:54:12.976 E/AndroidRuntime(16490): FATAL EXCEPTION: AppCenter.Looper
07-03 14:54:12.976 E/AndroidRuntime(16490): Process: com.rex.Poopy, PID: 16490
07-03 14:54:12.976 E/AndroidRuntime(16490): *java.lang.NoSuchMethodError: No interface method deserializeLog*(Ljava/lang/String;)Lcom/microsoft/appcenter/ingestion/models/Log; in class Lcom/microsoft/appcenter/ingestion/models/json/LogSerializer; or its super classes (declaration of 'com.microsoft.appcenter.ingestion.models.json.LogSerializer' appears in /data/app/com.rex.Poopy-AUKAlVfrCt1wkgFjCFanpw==/base.apk)
com.microsoft.appcenter.crashes.Crashes.initialize(Crashes.java:631)
com.microsoft.appcenter.crashes.Crashes.applyEnabledState(Crashes.java:352)
com.microsoft.appcenter.AbstractAppCenterService.onStarted(AbstractAppCenterService.java:201)
com.microsoft.appcenter.crashes.Crashes.onStarted(Crashes.java:367)
com.microsoft.appcenter.AppCenter.finishStartServices(AppCenter.java:662)
com.microsoft.appcenter.AppCenter.access$500(AppCenter.java:53)
com.microsoft.appcenter.AppCenter$7.run(AppCenter.java:642)
at android.os.Handler.handleCallback(Handler.java:789)
android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
android.os.HandlerThread.run(HandlerThread.java:65)
07-03 14:54:12.996 D/AppCenterCrashes(16490): Saving uncaught exception.
Loaded assembly: System.Reflection.TypeExtensions.dll [External]
07-03 14:54:13.029 D/AppCenterCrashes(16490): Saved JSON content for ingestion into /data/user/0/com.rex.Poopy/files/error/ac251825-af31-464a-ace5-782aa16c4085.json
Loaded assembly: System.Text.RegularExpressions.dll [External]
07-03 14:54:13.051 D/AppCenterCrashes(16490): Saved Throwable as is for client side inspection in /data/user/0/com.rex.Poopy/files/error/ac251825-af31-464a-ace5-782aa16c4085.throwable throwable:
07-03 14:54:13.051 D/AppCenterCrashes(16490): java.lang.NoSuchMethodError: No interface method deserializeLog(Ljava/lang/String;)Lcom/microsoft/appcenter/ingestion/models/Log; in class Lcom/microsoft/appcenter/ingestion/models/json/LogSerializer; or its super classes (declaration of 'com.microsoft.appcenter.ingestion.models.json.LogSerializer' appears in /data/app/com.rex.Poopy-AUKAlVfrCt1wkgFjCFanpw==/base.apk)
com.microsoft.appcenter.crashes.Crashes.initialize(Crashes.java:631)
com.microsoft.appcenter.crashes.Crashes.applyEnabledState(Crashes.java:352)
com.microsoft.appcenter.AbstractAppCenterService.onStarted(AbstractAppCenterService.java:201)
com.microsoft.appcenter.crashes.Crashes.onStarted(Crashes.java:367)
com.microsoft.appcenter.AppCenter.finishStartServices(AppCenter.java:662)
com.microsoft.appcenter.AppCenter.access$500(AppCenter.java:53)
com.microsoft.appcenter.AppCenter$7.run(AppCenter.java:642)
android.os.Handler.handleCallback(Handler.java:789)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by gunvld** [comment]
It seems to be fixed after cleaning bin and obj folder for the 12th time.. Before that didnt work even after clean and rebuild.
